### ISSUE TITLE
A question about the results of igate function.

### ISSUE THREAD

**Issue by clowdycurly** [stefan-stein/igate#2]
Firstly, thanks to the R package developed by the author, which has provided great help for my research. However, I have a question about whether I should ignore the variables whose **p** value is greater than 0.05 when the **count** value of which is greater than 6 in the results obtained by using the **igate** function.

**Comment by stefan-stein** [comment]
Hi @clowdycurly, 

I am glad to hear that igate is helping you in your research! In a case like this, it would be best to get input from a domain expert on the issue, if you have access to one: They can help you answer if it makes sense to have this variable as a predictor or not, if it is target leakage or not, etc.

If you do not have access to a domain expert, it will depend on what follow up analysis you are going to do. igate gives you an initial idea of which variables are potentially influential. Are you going to employ further variable selection techniques later on? Then you can keep it. Do you want to change production and only focus on the most impactful causes? Then it's probably best to ignore it. In short, in cases like this, it is important to take the overall analysis and the physical properties of the experiment under study into account.

Hope that helps!

Best,
Stefan

**Comment by clowdycurly** [comment]
> Hi @clowdycurly,
> 
> I am glad to hear that igate is helping you in your research! In a case like this, it would be best to get input from a domain expert on the issue, if you have access to one: They can help you answer if it makes sense to have this variable as a predictor or not, if it is target leakage or not, etc.
> 
> If you do not have access to a domain expert, it will depend on what follow up analysis you are going to do. igate gives you an initial idea of which variables are potentially influential. Are you going to employ further variable selection techniques later on? Then you can keep it. Do you want to change production and only focus on the most impactful causes? Then it's probably best to ignore it. In short, in cases like this, it is important to take the overall analysis and the physical properties of the experiment under study into account.
> 
> Hope that helps!
> 
> Best,
> Stefan

Thank you very much for your patient reply, which will be a great help to me.

**Comment by clowdycurly** [comment]
> I am glad to hear that igate is helping you in your research! In a case like this, it would be best to get input from a domain expert on the issue, if you have access to one: They can help you answer if it makes sense to have this variable as a predictor or not, if it is target leakage or not, etc.
> 
> If you do not have access to a domain expert, it will depend on what follow up analysis you are going to do. igate gives you an initial idea of which variables are potentially influential. Are you going to employ further variable selection techniques later on? Then you can keep it. Do you want to change production and only focus on the most impactful causes? Then it's probably best to ignore it. In short, in cases like this, it is important to take the overall analysis and the physical properties of the experiment under study into account.

Thank you very much for your patient and serious reply, it will be a great help for me.
